set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'macchiato'

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
bind C-b last-window

# Forward keys to terminal, used for some bindings in Neovim
set -g extended-keys always

run '~/.tmux/plugins/tpm/tpm'
